POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hdHRpIiwiaWQiOiI2YTE5NTRlZGVkNTcwNTA0NTM0MjYzZmQiLCJpYXQiOjE3ODAwNDUwNTJ9.Rgazi87bEyaaN8NvylCZ4iS0EQRfINJVL6Ms_g44Mp0

{
  "title": "toineasdasdn blogi kun on kirjautunut sisään user extractor middlewarella",
  "author": "asdads",
  "url": "osote3201asd"
}